// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvzfnctjyfwefxvyldjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2emZuY3RqeWZ3ZWZ4dnlsZGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNzc0NTksImV4cCI6MjA2Mjg1MzQ1OX0.VgUkBO3q57HABqNwlc6ZZ9gi_Jt_YXRKyqk02Q7WLqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);